#!/bin/bash

#https://www.cnblogs.com/EasonJim/p/7863099.html

#一、安装：

#1、安装zsh

sudo apt-get install zsh
#2、把默认的Shell改成zsh

chsh -s /bin/zsh
#注意：不要使用sudo。

#3、配置密码文件，解决chsh: PAM认证失败的问题

sudo vim /etc/passwd
#把第一行的/bin/bash改成/bin/zsh，这个是root用户的。


#把最后一行的/bin/bash改成/bin/zsh，这个应该是每台电脑的登录用户名+计算机名组成的。



#4、安装Git

sudo apt-get install git
#5、安装oh-my-zsh

#为什么要安装，用于快速配置zsh。

#官网：http://ohmyz.sh/

#离线版本：（链接: https://pan.baidu.com/s/1i5iqYhB 密码: v5c2），如果使用离线版本需要修改为可执行权限：sudo chmod +x *.sh

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
#6、重启电脑，查看效果

 

#7、安装autojump自动跳转插件

#官网：https://github.com/wting/autojump

#安装：

sudo apt-get install autojump
#配置教程：cat /usr/share/doc/autojump/README.Debian

#配置：

#vim .zshrc
#在最后一行加入，注意点后面是一个空格
echo '. /usr/share/autojump/autojump.sh' >> ~/.zshrc
#生效：

source ~/.zshrc
#8、安装zsh-syntax-highlighting语法高亮插件

#官网：https://github.com/zsh-users/zsh-syntax-highlighting

#安装：

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
echo "source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc
#生效：

source ~/.zshrc
#9、安装zsh-autosuggestions语法历史记录插件

#官网：https://github.com/zsh-users/zsh-autosuggestions

#安装：

git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
plugins=(zsh-autosuggestions)
#然后会发现上面这句话是不会生效的。这里科普一下：在~/.oh-my-zsh/plugins下有很多插件，直接使用plugins=(ant mvn svn git)这样的命令是可以直接加载插件的。

#经过研究发现，如果使用plugins去执行插件的，首先要在本机已经安装了这个软件之后才可以使用。且这种方式在Ubuntu下不支持命令去执行，只能放在.zshrc文件下使用，然后再通过source ~/.zshrc使其生效。这个是对于Ubuntu比较吭的地方。

#所以上面的plugins要放在~/.zshrc，具体修改如下：

vim ~/.zshrc
#增加插件：



#然后增加zsh的执行文件在最后一行：

source $ZSH_CUSTOM/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh


#生效：

source ~/.zshrc
#10、配置主题

#官方主题参考：https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes

sudo vim ~/.zshrc
#找到ZSH_THEME="robbyrussell"，修改为：ZSH_THEME="ys"；

#生效：

source ~/.zshrc
 

#二、卸载：

#执行：

#sudo sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/uninstall.sh)"
#把/etc/passwd改回bash：

#第一行的/bin/bash



#最后一行的/bin/bash



#其实看样子是很简单的卸载，但是最后你会发现还有很多没有干掉的，在使用上你会慢慢的发现。

 
